/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HW1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testRemoveVowels() {
        String[] names = { "silan", "melis", "oguzhan", "arkadas", "mailhesabim" };
        assertEquals("mlhsbm5@hotmail.com", App.createMailAddress(names, 4, 0, "hotmail"));
    }
    @Test
    public void testRemoveConsanant() {
        String[] names = { "silan", "melis", "oguzhan", "arkadas", "mailhesabim" };
        assertEquals("aaa4@hotmail.com", App.createMailAddress(names, 3, 1, "hotmail"));
    }
}
