/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HW1;

public class App {
    public String getGreeting() {
        return "Hello! ";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static String createMailAddress(String[] names, int index, Integer choice, String extension) { // 0-removeVowel, 1-dublicateVowel
                                                                                                        
        String name = names[index];
        String newName = "";
        int size = names[index].length();
        if (choice.equals(0)) {
            for (int i = 0; i < size; i++) {
                if (name.charAt(i) == 'a' || name.charAt(i) == 'e' || name.charAt(i) == 'i' || name.charAt(i) == 'o'
                        || name.charAt(i) == 'u') {
                    continue;
                } else
                    newName += name.charAt(i);
            }

        } else if(choice.equals(1)) {
            for(int i = 0; i < size ; i++ ) {
                if(name.charAt(i)=='a' || name.charAt(i)=='e' || name.charAt(i)=='i' || name.charAt(i)=='o' ||name.charAt(i)=='u') {
                    newName += name.charAt(i)+ "" + name.charAt(i);
                }
                else
                    newName += name.charAt(i);
            }
        }

        newName = newName + (index + 1) + "@" + extension + ".com";
        return newName;

    }

}
